# Generated by Django 5.0.1 on 2024-02-12 05:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_column="createdAt")),
                ("system", models.TextField()),
                ("voice", models.TextField()),
                ("transpose", models.FloatField()),
                ("playback", models.FloatField()),
                ("stability", models.FloatField(blank=True, null=True)),
                ("boost", models.FloatField(blank=True, null=True)),
                ("font_family", models.TextField(db_column="fontFamily")),
                ("font_size", models.IntegerField(db_column="fontSize")),
                ("stroke", models.IntegerField()),
                ("limit", models.IntegerField()),
                ("username", models.TextField()),
                ("picture", models.TextField()),
                ("background", models.TextField(blank=True, null=True)),
                (
                    "start_from",
                    models.IntegerField(blank=True, db_column="startFrom", null=True),
                ),
                ("soundtrack", models.TextField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("reddit", models.TextField(blank=True, null=True)),
                ("content", models.JSONField()),
                ("title", models.TextField()),
                ("url", models.TextField(blank=True, null=True)),
                (
                    "render_id",
                    models.TextField(
                        blank=True, db_column="renderId", null=True, unique=True
                    ),
                ),
                (
                    "audio_done",
                    models.BooleanField(blank=True, db_column="audioDone", null=True),
                ),
                (
                    "marks_done",
                    models.BooleanField(blank=True, db_column="marksDone", null=True),
                ),
                (
                    "audio_id",
                    models.TextField(
                        blank=True, db_column="audioId", null=True, unique=True
                    ),
                ),
                (
                    "marks_id",
                    models.TextField(
                        blank=True, db_column="marksId", null=True, unique=True
                    ),
                ),
                (
                    "audio_url",
                    models.TextField(blank=True, db_column="audioURL", null=True),
                ),
                ("marks", models.JSONField(blank=True, null=True)),
                ("status", models.TextField()),
                ("engine", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Story",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StoryDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("body", models.TextField()),
                ("raw_text", models.TextField()),
                ("is_edited", models.BooleanField(default=False)),
                ("is_highlighted", models.BooleanField(default=False)),
                ("highlights", models.TextField()),
                ("edited_story", models.TextField()),
                ("highlighted_story", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("url", models.URLField()),
            ],
        ),
    ]
